import { Resend } from "resend";

export const resend = new Resend(process.env.RESEND_API_KEY);

export async function sendReportEmail({
  to,
  pipelineName,
  reportTitle,
  periodStart,
  periodEnd,
  pdfBuffer,
}: {
  to: string[];
  pipelineName: string;
  reportTitle: string;
  periodStart: string;
  periodEnd: string;
  pdfBuffer: Buffer;
}) {
  const filename = `${pipelineName.toLowerCase().replace(/\s+/g, "-")}-${periodStart}-to-${periodEnd}.pdf`;

  await resend.emails.send({
    from: "Subterra Reports <reports@subterra.io>",
    to,
    subject: `${reportTitle} — ${periodStart} to ${periodEnd}`,
    html: `
      <div style="font-family: -apple-system, sans-serif; max-width: 500px; margin: 0 auto; padding: 40px 20px;">
        <div style="display: flex; align-items: center; gap: 10px; margin-bottom: 24px;">
          <div style="width: 28px; height: 28px; border-radius: 6px; background: linear-gradient(135deg, #6366f1, #8b5cf6); display: flex; align-items: center; justify-content: center;">
            <span style="color: white; font-weight: 800; font-size: 12px;">S</span>
          </div>
          <span style="font-size: 16px; font-weight: 800; color: #111;">subterra</span>
        </div>
        <h1 style="font-size: 20px; font-weight: 700; color: #111; margin-bottom: 8px;">
          ${reportTitle}
        </h1>
        <p style="color: #666; font-size: 14px; margin-bottom: 24px;">
          Report period: ${periodStart} — ${periodEnd}
        </p>
        <p style="color: #666; font-size: 14px; margin-bottom: 8px;">
          Your scheduled report is attached as a PDF.
        </p>
        <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;" />
        <p style="color: #999; font-size: 12px;">
          Generated by Subterra · Pipeline: ${pipelineName}
        </p>
      </div>
    `,
    attachments: [
      {
        filename,
        content: pdfBuffer,
        contentType: "application/pdf",
      },
    ],
  });
}
